# Name of workflow
name: Lint workflow
# Trigger workflow on all pull requests
on:
  pull_request:
    branches:
      - develop
      - staging
# Jobs to carry out
jobs:
  test:
    # Operating system to run job on
    runs-on: ubuntu-latest
    # Steps in job
    steps:
      # Get code from repo
      - name: Checkout code
        uses: actions/checkout@v3
      # Use Node.js 21.x
      - name: Use Node.js 21.x
        uses: actions/setup-node@v3
        with:
          node-version: 21.x
      # Install dependencies
      - name: :toolbox: Install dependencies
        run: npm install
      # Run lint
      - name: Run lint
        run: npm run lint

